/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'jarl' at '08-04-16 20:57' with Gradle 2.12
 *
 * @author jarl, @date 08-04-16 20:57
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
