/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'jarl' at '08-04-16 20:57' with Gradle 2.12
 *
 * @author jarl, @date 08-04-16 20:57
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
